name: Build and Deploy Gatsby

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          yarn install --ignore-scripts --network-timeout 100000
          cd node_modules/node-sass
          node scripts/install.js
          cd ../..

      - name: Build Gatsby
        run: yarn build
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          user_name: dosanHoon
          user_email: hangru1106@gmail.com
          commit_message: 'deploy: auto build from develop'
