name: Build and Deploy Gatsby

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    env:
      PYTHON: python3
      npm_config_python: python3
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Setup build tools
        run: |
          npm install -g node-gyp@9
          npm config set python python3

      - name: Install dependencies
        run: yarn install --network-timeout 100000 || yarn install --network-timeout 100000 --ignore-engines

      - name: Build Gatsby
        run: yarn build
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          user_name: dosanHoon
          user_email: hangru1106@gmail.com
          commit_message: 'deploy: auto build from develop'
